# Data Exploration and Preprocessing

In [1]:
import pandas as pd
import duckdb
from pathlib import Path

## Data setup

Make sure data has been downloaded and processed, instruction can be found in `README.md`

## Dataset Overview

### Full dataset

In [2]:
# fields in reviews file
duckdb.query("""
       DESCRIBE SELECT * FROM "../data/raw/Books.parquet";
""")

┌───────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────┬─────────┬─────────┬─────────┐
│    column_name    │                                                  column_type                                                  │  null   │   key   │ default │  extra  │
│      varchar      │                                                    varchar                                                    │ varchar │ varchar │ varchar │ varchar │
├───────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────────┼─────────┼─────────┼─────────┤
│ rating            │ DOUBLE                                                                                                        │ YES     │ NULL    │ NULL    │ NULL    │
│ title             │ VARCHAR                                                                                                       │ YES     │ NULL    │ NULL    │ NULL    │
│ text              │ VARCHAR                                                                                                       │ YES     │ NULL    │ NULL    │ NULL    │
│ images            │ STRUCT(small_image_url VARCHAR, medium_image_url VARCHAR, large_image_url VARCHAR, attachment_type VARCHAR)[] │ YES     │ NULL    │ NULL    │ NULL    │
│ asin              │ VARCHAR                                                                                                       │ YES     │ NULL    │ NULL    │ NULL    │
│ parent_asin       │ VARCHAR                                                                                                       │ YES     │ NULL    │ NULL    │ NULL    │
│ user_id           │ VARCHAR                                                                                                       │ YES     │ NULL    │ NULL    │ NULL    │
│ timestamp         │ BIGINT                                                                                                        │ YES     │ NULL    │ NULL    │ NULL    │
│ helpful_vote      │ BIGINT                                                                                                        │ YES     │ NULL    │ NULL    │ NULL    │
│ verified_purchase │ BOOLEAN                                                                                                       │ YES     │ NULL    │ NULL    │ NULL    │
└───────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────┴─────────┴─────────┴─────────┘
  10 rows                                                                                                                                                         6 columns

In [3]:
# number of reviews
duckdb.query("""
       SELECT COUNT(*) FROM "../data/raw/Books.parquet";
""")

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│     29475453 │
└──────────────┘

In [4]:
# fields in meta books files
duckdb.query("""
       DESCRIBE SELECT * FROM "../data/raw/meta_Books.parquet";
""")

┌─────────────────┬───────────────────────────────────────────────────────────────────────────┬─────────┬─────────┬─────────┬─────────┐
│   column_name   │                                column_type                                │  null   │   key   │ default │  extra  │
│     varchar     │                                  varchar                                  │ varchar │ varchar │ varchar │ varchar │
├─────────────────┼───────────────────────────────────────────────────────────────────────────┼─────────┼─────────┼─────────┼─────────┤
│ main_category   │ VARCHAR                                                                   │ YES     │ NULL    │ NULL    │ NULL    │
│ title           │ VARCHAR                                                                   │ YES     │ NULL    │ NULL    │ NULL    │
│ subtitle        │ VARCHAR                                                                   │ YES     │ NULL    │ NULL    │ NULL    │
│ author          │ STRUCT(avatar VARCHAR, "name" VARCHAR, about VARCHAR[])                   │ YES     │ NULL    │ NULL    │ NULL    │
│ average_rating  │ DOUBLE                                                                    │ YES     │ NULL    │ NULL    │ NULL    │
│ rating_number   │ BIGINT                                                                    │ YES     │ NULL    │ NULL    │ NULL    │
│ features        │ VARCHAR[]                                                                 │ YES     │ NULL    │ NULL    │ NULL    │
│ description     │ VARCHAR[]                                                                 │ YES     │ NULL    │ NULL    │ NULL    │
│ price           │ JSON                                                                      │ YES     │ NULL    │ NULL    │ NULL    │
│ images          │ STRUCT("large" VARCHAR, variant VARCHAR, thumb VARCHAR, hi_res VARCHAR)[] │ YES     │ NULL    │ NULL    │ NULL    │
│ videos          │ STRUCT(title VARCHAR, url VARCHAR, user_id VARCHAR)[]                     │ YES     │ NULL    │ NULL    │ NULL    │
│ store           │ VARCHAR                                                                   │ YES     │ NULL    │ NULL    │ NULL    │
│ categories      │ VARCHAR[]                                                                 │ YES     │ NULL    │ NULL    │ NULL    │
│ details         │ MAP(VARCHAR, JSON)                                                        │ YES     │ NULL    │ NULL    │ NULL    │
│ parent_asin     │ VARCHAR                                                                   │ YES     │ NULL    │ NULL    │ NULL    │
│ bought_together │ JSON                                                                      │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────────┴───────────────────────────────────────────────────────────────────────────┴─────────┴─────────┴─────────┴─────────┘
  16 rows                                                                                                                   6 columns

In [5]:
# number of books
duckdb.query("""
       SELECT COUNT(*) FROM "../data/raw/meta_Books.parquet";
""")

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│      4448181 │
└──────────────┘

### Smaller dataset, only include top rated books

In [6]:
# number of reviews
duckdb.query("""
       SELECT COUNT(*) FROM "../data/raw/top_Books.parquet";
""")

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│        41562 │
└──────────────┘

In [7]:
# number of books
duckdb.query("""
       SELECT COUNT(*) FROM "../data/raw/top_meta_Books.parquet";
""")

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│        10000 │
└──────────────┘

## Sample Records

### Review Records

In [8]:
books = pd.read_parquet("../data/raw/top_Books.parquet",)
books.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5.0,... wrong with Spurgeon's his insights to the ...,You cannot go wrong with Spurgeon's his insigh...,[],1903087082,1903087082,AGGJ6SHNO3HLK5JODWEITQQJETKQ,1423577380000,0,True
1,5.0,Great book,Great book and seller. Highly recommended,[],0899064418,0899064418,AHIVLNOQSDCSVO5LXFJA27MPORIA,1546398296723,0,True
2,5.0,No let downs here!!!,Full of great stories. Finally got to read Cam...,[],0517336359,0517336359,AFEMVUNGJXKV5HA463WSDY4I2K7Q,1471377349000,3,False
3,5.0,Fun way to get science info.,A cute little ‘cookbook’ for kids that gives g...,[],1455625116,1455625116,AFAYQWKMEVX7GKQ7GZNQXJ7ORLWA,1611222079367,0,True
4,5.0,Super intro to Indian flavors ....,I've been a huge fan of Indian food ever since...,[],078181331X,078181331X,AHRGTIMQO47C2VLJILIDU53BQKSA,1411268684000,0,False

In [9]:
books.tail()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
41557,5.0,Five Stars,Prayers God wants to hear and answer!,[],1576733734,1576733734,AE4D7E2TRYF3JOIWT443TNCMVEEQ,1513639969855,0,True
41558,5.0,Great Book!,"Love the book, went to three different book st...",[],1576733734,1576733734,AHPFF2ALWPSOAOWHRAQQ3GHOIX5A,1287872570000,1,True
41559,5.0,"Worth the buy, well worth the read",Bought this book for my nephew and brother-in-...,[],0578879778,0578879778,AEHOT34INUXNCLE6US4REM3AE7EA,1627011047267,0,True
41560,5.0,Excellent Resource,This is an excellent resource!!! This book pro...,[],1641137843,1641137843,AHGDLHWRZ6A6X7HUGV5NS2CZI7IQ,1571950455207,1,False
41561,5.0,Just finished reading and already hoping the a...,I was fortunate to stumble upon the author's b...,[],B0C641MNXW,B0C641MNXW,AHT2N4PSRZFBUXQ6WHBOS6VRGKEQ,1691369328698,0,False

### Meta Book Records

In [10]:
meta_books = pd.read_parquet("../data/raw/top_meta_Books.parquet")
meta_books.head()

,main_category,title,subtitle,author,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together
0,Books,Beautifully Imperfect: Pulchritudinous,"Paperback – May 9, 2022",None,5.0,11,[“Beautifully Imperfect” is a book written by ...,[],b'10.99',[],[],"Hannah Michelle (Author), Sabrina Blair (Illu...","[Books, Literature & Fiction, Poetry]","[(Publisher, b'""Courteous Publications (May 9,...",0978516648,None
1,Books,Charlie Goes to the Doctor (Get Healthy Kids),"Paperback – Illustrated, June 14, 2021",{'avatar': 'https://m.media-amazon.com/images/...,5.0,20,[Who really likes to get sick or be taken to t...,[],b'19.95',[{'large': 'https://m.media-amazon.com/images/...,[],"Dr. Dona Cooper-Dockery (Author), Donnel Dock...","[Books, Children's Books, Growing Up & Facts o...","[(Publisher, b'""Cooper Internal Medicine (June...",099733794X,None
2,Books,Cats in the Country 2020 Calendar,"Calendar – Wall Calendar, April 1, 2019",None,5.0,15,[],[],"b'""from 16.72""'",[{'large': 'https://m.media-amazon.com/images/...,[],"Inc. Lang Companies (Author), Susan Bourdet (...","[Books, Crafts, Hobbies & Home, Pets & Animal ...","[(Publisher, b'""Lang Holdings Inc (April 1, 20...",1469409178,None
3,Books,VW Beetle Calendar- Calendars 2021 - 2022 Wall...,"Calendar – Wall Calendar, July 30, 2021",None,5.0,27,[The legendary Volkswagen bug is captured on t...,[],"b'""from 44.99""'",[{'large': 'https://m.media-amazon.com/images/...,[],MegaCalendars (Author),"[Books, Arts & Photography, Photography & Video]","[(Publisher, b'""Dream Publishing; 2022nd editi...",1839412852,None
4,Books,The Unlikely President: He Won the Election. B...,"Paperback – September 27, 2022",{'avatar': 'https://m.media-amazon.com/images/...,5.0,11,"[In Stephen Palmer's debut novel,, The Unlikel...",[],b'18.99',[],[],Stephen Palmer (Author),"[Books, Literature & Fiction, Genre Fiction]","[(Publisher, b'""Independently published (Septe...",B0BGNDYVM4,None

In [11]:
meta_books.tail()

,main_category,title,subtitle,author,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together
9995,Books,Gun Trucks: A Visual History of the U.S. Army'...,"Paperback – January 1, 2015",None,5.0,11,[Gun Trucks US Army's Vietnam-Era Wheeled Esco...,[],b'29.99',[{'large': 'https://m.media-amazon.com/images/...,[],David Doyle (Author),"[Books, History, Military]","[(Publisher, b'""Ampersand Publishing (January ...",0986112739,None
9996,Books,Janet's Creative Style,"Paperback – Large Print, May 1, 2023",{'avatar': 'https://m.media-amazon.com/images/...,5.0,13,"[This is a story, based on true events, about ...",[],b'11.99',[],[],Kimberly Topping Burnside (Author),"[Books, Children's Books, Activities, Crafts &...","[(Publisher, b'""Burnside Publishing (May 1, 20...",B0C2RX8S5F,None
9997,Books,Animal Hugs & Kisses - Hawaii,"Paperback – Large Print, December 4, 2015",None,5.0,15,[Jordan and Kobe are young sisters who were bo...,[],b'12.98',[{'large': 'https://m.media-amazon.com/images/...,[],"Terry Lee (Author), Kobe Lee (Author), Jorda...","[Books, Children's Books, Animals]","[(Publisher, b'""CreateSpace Independent Publis...",1514849100,None
9998,Books,All the Way Down: Amazon Rainforest,"Hardcover – May 4, 2021",{'avatar': 'https://m.media-amazon.com/images/...,5.0,18,[All The Way Down is an ingenious new informat...,"[About the Author, Alex Woolf studied history ...",b'16.95',[{'large': 'https://m.media-amazon.com/images/...,[],"Alex Woolf (Author), Isobel Lundie (Illustrator)","[Books, Children's Books, Science, Nature & Ho...","[(Publisher, b'""Book House (May 4, 2021)""'), (...",1913337987,None
9999,Books,Sanctuaries,"Paperback – February 25, 2023",{'avatar': 'https://m.media-amazon.com/images/...,5.0,11,[A new novel from an award-winning writer abou...,"[Review, ""Sgambati's prose is fluid and evocat...",b'18.0',[],[],Vince Sgambati (Author),"[Books, LGBTQ+ Books, Literature & Fiction]","[(Publisher, b'""Standing Stone Books (February...",B0BXZ6FS16,None

## Selection of Fields and Justification

From the review data, we will keep only asin, text, and rating. We think this in

Which fields we are keeping and removing

- Book reviews
  - KEEP
    - rating: this is helpful information to display when looking up books
    - text: this is helpful information to display when looking up books
    - asin: to connect the review to the book data
  - REMOVE
    - title: this is already in meta data
    - images: we don't be displaying images in our simple search app
    - user_id: this isn't relevant information for our search app
    - timestamp: this isn't relevant information for our search app
    - helpful_vote: this could be helpful information to use in the future but we are just keeping it simple for now
    - verified_purchase: this could be helpful information to use in the future but we are just keeping it simple for now
- Book meta data
  - KEEP
    - title: key information
    - author: keep author name but remove image and bio, the image we won't be using in this simple app and the bio might get confused with book info in dense encodings (searching for a book about Ireland might return books that are not from Ireland but are by an Irish writer)
    - average_rating: helpful information to view
    - rating_number: needed to context for average rating
    - features: this is the feature that gives the best book description, one of the most important features for searching
    - price: helpful information to view
    - parent_asin: needed to find the relevant reviews
    - categories: give genre information, this is also helpful for search
  - REMOVE
    - main_category: inconsistent information, generally says the book format which isn't important for this book search app
    - subtitle: inconsistent information, also information on format
    - description: mix of reviews and description info, not very consistent or of high quality
    - images: not needed for this search app
    - video: not needed for this search app
    - store: inconsistent data and not needed for the search app
    - details: publisher information, not needed for this search app
    - bought_together: amazon purchase information, not needed for this search app

## Text Preprocessing Decisions

Within the bm25 search with langchain we have the following text preprocessing:

- making all text lowercase
- removing all characters that are not a-z and 0-9
- removing common stopwords

For the FAISS semantic search we did not preprocess the text because capitalization, punctuation, stopwords etc all provide context for the embedder.

## Final data format

In [12]:
check_reviews = duckdb.query("""
    SELECT *
    FROM "../data/processed/merged.parquet"
    WHERE rating_order == 1
    LIMIT 10
    """
)

display(check_reviews.df())

,title,author,book_details,categories,average_rating,rating_number,price,individual_review,individual_rating,asin,rating_order
0,Jim Henson s Muppet Babies : Baby Piggy s Merm...,,Vintage children's book,,5.0,12,13.39,perfect condition. Brought back many memories...,5.0,B000MPRI44,1
1,Hank Marvin & John Farrar,Marvin & Farrar,2007 Digitally Remastered Reissue of Album by ...,"Books, Arts & Photography, Music",5.0,11,"""from 70.89""","Okay, let's get the nonsense out of the way fi...",5.0,B000PUB23E,1
2,The Fourth Floor: An Account of the Castro Com...,,,,5.0,12,977.87,Great book. Details the truth of what really ...,5.0,B000ZPJDFS,1
3,A Tippy Canoe and Canada Too,Sam Campbell,A Tippy Canoe and Canada Too [Paperback] [Jan ...,"Books, Children's Books, Literature & Fiction",5.0,17,9.94,Another fun and heart warming adventure of Sam...,5.0,B0012G00E2,1
4,My Turn on Earth,Carol Lynn Pearson,,,5.0,39,167.93,A very good book. So glad I purchased it.,5.0,B0017OE7I4,1
5,Bambi a Life in the Woods 1ST Edition American,Felix Salten,,,5.0,12,84.94,This review is for the original 293-page editi...,5.0,B0018EFAFM,1
6,Space (Pop-Up Facts) (August 2008),Peter Bond,,,5.0,11,NaN,I have the best arguments with my 5 year old s...,5.0,B001F296Q6,1
7,"1970 Chevelle, El Camino, Malibu and SS Owner'...",,COVERS ALL 1970 CHEVELLE MODELS,"Books, Engineering & Transportation, Transport...",5.0,13,27.95,I have a 1970 Chevelle SS LS-6 convertible and...,5.0,B00435MVP0,1
8,"O, Gigantic Victory! Baseball Poems: The 2010 ...",Steve Hermanos,"Jon Miller, Hall Of Famer: Your humor dryer, T...","Books, Sports & Outdoors, Baseball",5.0,15,5.11,It took the Giants some 53 years to win a Worl...,5.0,B004H31AVE,1
9,THE NATIVE ORCHIDS OF FLORIDA,Carlyle A. Luer,,,5.0,15,NaN,Just learning about orchids and am enjoying th...,5.0,B006REU5EE,1